export const API_URL_REGISTRO = "http://localhost/apiRegistro"
export const GOOGLE_API_KEY = "AIzaSyDNFiAeFUFT0B9GinyWk9DwcDkeNJoWO5s"
export const API_URL_REGISTRO_STUDENTI = API_URL_REGISTRO + "/studenti"
export const API_URL_REGISTRO_PRESENZE = API_URL_REGISTRO + "/presenze"
export const API_URL_REGISTRO_DOCENTI = API_URL_REGISTRO + "/docenti"
export const API_URL_REGISTRO_GESTORI = API_URL_REGISTRO + "/gestori"
export const API_URL_REGISTRO_EDIZIONI = API_URL_REGISTRO + "/edizioni"