export const Constants = {
    CANCEL_TEXT: "Annulla",
    OK_TEXT: "Ok",
    CONFIRM_TEXT: "Conferma",
    BACK_TEXT: "Indietro",
    FORWARD_TEXT: "Avanti",
    INFO_TEXT: "Info",
    CLOSE_TEXT: "Chiudi",
    WARNING_TEXT: "Attenzione!",
    ERROR_TEXT: "Errore!",
    SUCCESS_TEXT: "Complimenti!",
    YESY_TEXT: "Sì",
    NO_TEXT: "No",
    LOADING_TEXT: "Caricamento...",
    SEARCH_PLACEHOLDER: "Cerca",
    FILTER_TEXT: "Filtra",
    RESET_INPUT_TEXT: "Pulisci",
    TOGGLE_PASSWORD_TEXT: "Mostra",
    INCREASE_TEXT: "Aumenta",
    DECREASE_TEXT: "Riduci",
    PREV_TEXT: "Precedente",
    NEXT_TEXT: "Successivo",
    CHANGE_MONTH: "Cambia mese",
    CHANGE_YEAR: "Cambia anno",
    UPLOAD_FILE_LABEL: "Carica un file",
    UPLOAD_FILE_DROP_LABEL: "Carica o trascina un file",
    UPLOAD_FILE_ERROR_NOT_MULTIPLE: "Puoi caricare soltanto un file!",
    SELECTED_FILES_LABEL: "File selezionati:",
}