export const Constants = {
    CANCEL_TEXT: "Annulla",
    OK_TEXT: "Ok",
    CONFIRM_TEXT: "Conferma",
    BACK_TEXT: "Indietro",
    FORWARD_TEXT: "Avanti",
    INFO_TEXT: "Info",
    CLOSE_TEXT: "Chiudi",
    WARNING_TEXT: "Attenzione!",
    ERROR_TEXT: "Errore!",
    SUCCESS_TEXT: "Complimenti!",
    YESY_TEXT: "Sì",
    NO_TEXT: "No",
    LOADING_TEXT: "Caricamento...",
    SEARCH_PLACEHOLDER: "Cerca",
    FILTER_TEXT: "Filtra",
    RESET_INPUT_TEXT: "Pulisci",
}