export class ComponentsPaths{
    static SITE_BASE = "/"
    static ERROR_404_PATH = "404"
    static PATH_COORDINATORI = ComponentsPaths.SITE_BASE + "coordinatori"
    static PATH_COORDINATORI_LOGIN = ComponentsPaths.PATH_COORDINATORI + "/login"
    static PATH_COORDINATORI_HOME = ComponentsPaths.PATH_COORDINATORI + "/home"
    static PATH_COORDINATORI_LISTA_STUDENTI = ComponentsPaths.PATH_COORDINATORI + "/studenti"
    static PATH_COORDINATORI_ADD_STUDENTE = ComponentsPaths.PATH_COORDINATORI + "/studenti/new"
    static PATH_COORDINATORI_EDIT_STUDENTE_BASE = ComponentsPaths.PATH_COORDINATORI + "/studenti/edit"
    static PATH_COORDINATORI_EDIT_STUDENTE = ComponentsPaths.PATH_COORDINATORI_EDIT_STUDENTE_BASE + "/:id"
    static PATH_COORDINATORI_DETAILS_STUDENTE = ComponentsPaths.PATH_COORDINATORI + "/studenti/:id"
    static PATH_COORDINATORI_IMPORT_STUDENTI = ComponentsPaths.PATH_COORDINATORI + "/studenti/import"
    static PATH_COORDINATORI_LISTA_MATERIE = ComponentsPaths.PATH_COORDINATORI + "/materie"
    static PATH_COORDINATORI_LISTA_DOCENTI = ComponentsPaths.PATH_COORDINATORI + "/docenti"
    static PATH_COORDINATORI_ADD_DOCENTE = ComponentsPaths.PATH_COORDINATORI + "/docenti/new"
    static PATH_COORDINATORI_EDIT_DOCENTE_BASE = ComponentsPaths.PATH_COORDINATORI + "/docenti/edit"
    static PATH_COORDINATORI_EDIT_DOCENTE = ComponentsPaths.PATH_COORDINATORI_EDIT_DOCENTE_BASE + "/:id"
}